### ISSUE TITLE
include_reference_token and refreshable not working when configured by default

### ISSUE THREAD

**Issue by loicgreffier** [jfrog/vault-plugin-secrets-artifactory#154]
**Describe the bug**

When configuring the user_token with `include_reference_token` and `refreshable` parameters set to `true`, requesting a user token seems to not return the `reference_token` and `refresh_token` by default.

**To Reproduce**

1. Configure the user_token

```
vault write artifactory/config/user_token max_ttl=600 default_ttl=600 include_reference_token=true refreshable=true
```

2. Check it has been activated

```
Key                        Value
---                        -----
audience                   n/a
default_description        Generated by Vault
default_ttl                10m
include_reference_token    true
max_ttl                    10m
refreshable                true
```

3. Request a token

```
vault read artifactory/user_token/myUser
```

4. In the response, reference token and refresh token are missing

```
Key                Value
---                -----
...
reference_token    n/a
refresh_token      n/a
...
```

However, when specifying the include_reference_token and refreshable parameters when requesting the token

```
vault read artifactory/user_token/myUser include_reference_token=true refreshable=true
```

It works, the tokens are returned as expected

**Requirements for and issue**
- Artifactory 7.68.19
- Vault 1.15.5
- Vault Plugin 1.2.0

**Expected behavior**
I was expecting to not having to specify the parameters when requesting the token, as they were defined to `true` on the default configuration. Is this current behaviour the expected behaviour, or did I miss something ?

**Comment by loicgreffier** [comment]
@alexhung Thank you for the information, the issue can be closed I guess

**Comment by alexhung** [comment]
@loicgreffier Let's keep it open until the updates are released 😄
