### ISSUE TITLE
Bump version to 1.0.0

### ISSUE THREAD

**Issue by alexhung** [jfrog/vault-plugin-secrets-artifactory#76]
The JFrog team feels that we have reached a reasonable point to declare this plugin 'released' as 1.0.0.

Pros:
- Allows finer control of SemVer. i.e. we now have 'patch' version field to use.

Cons:
- Nothing material or functional

Please leave comment if you feel otherwise.

**Comment by TJM** [comment]
It might be good to have someone who is not intimately familiar with the inner workings to try installing it using the documentation (README) to see if it needs any help before going 1.0? .. you know to make sure it is "release quality" :)

**Comment by alexhung** [comment]
Agree! I will get @danielmkn to do a run through 😄
