### ISSUE TITLE
Renaming repository

### ISSUE THREAD

**Issue by alexhung** [jfrog/vault-plugin-secrets-artifactory#80]
Rename this repository from `artifactory-secrets-plugin` to `vault-plugin-secrets-artifactory`, following the same pattern as other Vault plugin repos (as well as Terraform provider).

Other references to the original name (binary name, path, etc.) would not be affected by this repo name change.

**Comment by TJM** [comment]
**AGREED**!!!

**Comment by TJM** [comment]
Based on what I am seeing at [hashicorp](https://github.com/orgs/hashicorp/repositories?q=vault-plugin&type=all&language=&sort=), it should be

`vault-plugin-secrets-artifactory`

So, "secrets" instead of "secret" ... but yes, I think it would make good sense to do this *BEFORE* going 1.0.0 ;)

**Comment by alexhung** [comment]
The reason I chose singular form is because when you do `vault plugin list` you get:

```
redis-elasticache-database-plugin    database    v0.1.0+builtin
redshift-database-plugin             database    v1.12.2+builtin.vault
snowflake-database-plugin            database    v0.6.1+builtin
ad                                   secret      v0.14.0+builtin
alicloud                             secret      v0.13.0+builtin
artifactory-secrets-plugin           secret      v0.2.17-dev+c28e2f9
```

So the type is `secret` but I just noticed that HashiCorp's repo is plural: https://github.com/hashicorp/vault-plugin-secrets-kv

**Comment by TJM** [comment]
I am sure it's good either way, one other thing to remember would be to update the integrations page: https://developer.hashicorp.com/vault/integrations
